--
-- Estructura de tabla para la tabla `glo_tc_maestro`
--
DROP TABLE IF EXISTS `bd_condominio`.`glo_tc_maestro`;
CREATE TABLE `bd_condominio`.`glo_tc_maestro` (
  `tc_maestro_id` int NOT NULL AUTO_INCREMENT,
  `tc_variable` varchar(45) NOT NULL,
  `tc_categoria1` varchar(45) NOT NULL,
  `tc_categoria2` varchar(45) NOT NULL,
  `tc_categoria3` varchar(250) NOT NULL,
  PRIMARY KEY (`tc_maestro_id`)
) ENGINE=InnoDB AUTO_INCREMENT=57 DEFAULT CHARSET=utf8mb3;
--
-- Volcado de datos para la tabla `glo_tc_maestro`
--
LOCK TABLES `bd_condominio`.`glo_tc_maestro` WRITE;
INSERT INTO `bd_condominio`.`glo_tc_maestro`  VALUES
(1,  'MAESTRO', 'ESTADO',   'ACTIVO'),
(2,  'MAESTRO', 'ESTADO',   'INACTIVO'),
(3,  'MAESTRO', 'CARGO',    'PILOTO DE BUS ALIMENTADOR'),
(4,  'MAESTRO', 'CARGO',    'PILOTO DE BUS ARTICULADO'),
(5,  'MAESTRO', 'CARGO',    'GESTOR DE PREVENCION'),
(6,  'MAESTRO', 'CARGO',    'ANALISTA DE MANTENIMIENTO'),
(7,  'MAESTRO', 'PERFIL',   'PILOTO'),
(8,  'MAESTRO', 'PERFIL',   'PERSONAL OPERACIONES'),
(9,  'MAESTRO', 'PERFIL',   'PERSONAL MANTENIMIENTO'),
(10, 'MAESTRO', 'CARGO',    'COORDINADOR DE PROGRAMACION'),
(11, 'MAESTRO', 'DISTRITO', 'PUENTE PIEDRA'),
(12, 'MAESTRO', 'DISTRITO', 'LOS OLIVOS'),
(13, 'MAESTRO', 'DISTRITO', 'COMAS'),
(14, 'MAESTRO', 'DISTRITO', 'SAN JUAN DE LURIGANCHO'),
(15, 'MAESTRO', 'DISTRITO', 'CARABAYLLO'),
(16, 'MAESTRO', 'DISTRITO', 'SAN MARTIN DE PORRES'),
(17, 'MAESTRO', 'DISTRITO', 'INDEPENDENCIA'),
(18, 'MAESTRO', 'DISTRITO', 'BREÑA'),
(19, 'MAESTRO', 'DISTRITO', 'CHORRILLOS'),
(20, 'MAESTRO', 'DISTRITO', 'CHOSICA'),
(21, 'MAESTRO', 'DISTRITO', 'VENTANILLA'),
(22, 'MAESTRO', 'DISTRITO', 'RIMAC'),
(23, 'MAESTRO', 'DISTRITO', 'VILLA EL SALVADOR'),
(24, 'MAESTRO', 'DISTRITO', 'CALLAO'),
(25, 'MAESTRO', 'DISTRITO', 'ATE VITARTE'),
(26, 'MAESTRO', 'DISTRITO', 'VILLA MARIA DEL TRIUNFO'),
(27, 'MAESTRO', 'DISTRITO', 'SURCO'),
(28, 'MAESTRO', 'DISTRITO', 'CERCADO DE LIMA'),
(29, 'MAESTRO', 'DISTRITO', 'LA MOLINA'),
(30, 'MAESTRO', 'DISTRITO', 'SAN BORJA'),
(31, 'MAESTRO', 'DISTRITO', 'SANTA ANITA'),
(32, 'MAESTRO', 'DISTRITO', 'CIENEGUILLA'),
(33, 'MAESTRO', 'DISTRITO', 'SANTIAGO DE SURCO'),
(34, 'MAESTRO', 'DISTRITO', 'ANCON'),
(35, 'MAESTRO', 'DISTRITO', 'HUAROCHIRI'),
(36, 'MAESTRO', 'DISTRITO', 'CHACLACAYO'),
(37, 'MAESTRO', 'CARGO',    'PROGRAMADOR MANTENIMIENTO'),
(38, 'MAESTRO', 'CARGO',    'PROGRAMADOR');
UNLOCK TABLES;
